Paginacion administrador
yanina-rodriguez-dev/veterinaria-frontend pull request #45
Opened 2023-08-06 03:29 UTC by federl94

Se agrega la funcionalidad de paginación a los reads de Administrador, admTurnos, admPacientes y admUsuarios. Se solicita merge a dev.

2023-08-06 20:04 UTC, maxivega0 requested changes
Dejo un par de errores en el codigo que hacen que no funcione la vista de usuario, las demas funcionan correctamente!

2023-08-06 20:04 UTC, maxivega0 commented on src/components/views/Usuarios/TablaGestionUsuarios.jsx
> +  const pacientesPaginados = pacientes.slice(startIndex, endIndex);
falta cambiar nombre a la variable "pacientesPaginados" y "pacientes.slice" por usuarios

2023-08-06 20:04 UTC, maxivega0 commented on src/components/views/Usuarios/TablaGestionUsuarios.jsx
> +  const [pacientes] = useState([]);
useState innecesario

2023-08-06 20:04 UTC, maxivega0 commented on src/components/views/Usuarios/TablaGestionUsuarios.jsx
>        <Table striped bordered size="sm" responsive className="text-center">
Corregir en la tabla el map, cambiar de "usuarios.map" a "usuariosPaginados.map"

2023-08-07 02:12 UTC, federl94 commented
Se solicita el pull con las correcciones solicitadas por @maxivega0 ! Gracias maxi. Testear.

2023-08-08 02:17 UTC, yanina-rodriguez-dev approved these changes

2023-08-08 02:17 UTC, merged