Maquetado acerca de
yanina-rodriguez-dev/veterinaria-frontend pull request #9
Opened 2023-07-20 22:55 UTC by AzulDP

Pido pull request para unir la pagina de acerca de nosotros a dev, gracias compas :)

2023-07-21 04:07 UTC, federl94 requested changes
Modificar lalínea que contiene los botones del carrousel, esta como showcontrols touch y es todo junto (showcontrolstouch) para evitar el warning en consola. Además, poner todas las imágenes del carrousel del mismo tamaño para evitar cambios de vista mientras funciona el carrousel. Lo demás, todo ok.

2023-07-21 09:36 UTC, AzulDP commented
gracias @federl94 aca mando corregida la rama para el merge. :)

2023-07-21 22:21 UTC, federl94 approved these changes

2023-07-24 03:06 UTC, closed without merging

2023-07-24 03:07 UTC, federl94 commented
Se cierra el pull request ya que hubo modificaciones y hay que actualizar la rama. Por favor crear un nuevo pull